# Generated by Django 4.0.5 on 2022-07-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_userchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatmessage',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
