# Generated by Django 4.0.5 on 2022-07-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_userchatmessage_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatmessage',
            name='timestamp',
        ),
    ]
