# Generated by Django 4.0.5 on 2022-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_userchatmessage_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmessage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userchatmessage',
            name='timestamp',
            field=models.FloatField(default=1659286085.2210705),
        ),
    ]
